-- Türkiye üniversiteleri (devlet + vakıf). Idempotent: önce 0006 migration'ını çalıştır.
-- universities_name_key benzersizlik kısıtı sayesinde tekrar eklenmez.

insert into universities (name, city) values
-- Ankara
('Ankara Üniversitesi', 'Ankara'),
('Hacettepe Üniversitesi', 'Ankara'),
('Gazi Üniversitesi', 'Ankara'),
('Orta Doğu Teknik Üniversitesi', 'Ankara'),
('Ankara Yıldırım Beyazıt Üniversitesi', 'Ankara'),
('Ankara Hacı Bayram Veli Üniversitesi', 'Ankara'),
('Ankara Sosyal Bilimler Üniversitesi', 'Ankara'),
('Ankara Müzik ve Güzel Sanatlar Üniversitesi', 'Ankara'),
('Bilkent Üniversitesi', 'Ankara'),
('Başkent Üniversitesi', 'Ankara'),
('TOBB Ekonomi ve Teknoloji Üniversitesi', 'Ankara'),
('Atılım Üniversitesi', 'Ankara'),
('Çankaya Üniversitesi', 'Ankara'),
('Ufuk Üniversitesi', 'Ankara'),
('Ankara Medipol Üniversitesi', 'Ankara'),
('Lokman Hekim Üniversitesi', 'Ankara'),
('Türk Hava Kurumu Üniversitesi', 'Ankara'),
('Ostim Teknik Üniversitesi', 'Ankara'),
('Ankara Bilim Üniversitesi', 'Ankara'),
('Yüksek İhtisas Üniversitesi', 'Ankara'),
-- İstanbul
('İstanbul Üniversitesi', 'İstanbul'),
('İstanbul Üniversitesi-Cerrahpaşa', 'İstanbul'),
('İstanbul Teknik Üniversitesi', 'İstanbul'),
('Boğaziçi Üniversitesi', 'İstanbul'),
('Marmara Üniversitesi', 'İstanbul'),
('Yıldız Teknik Üniversitesi', 'İstanbul'),
('Mimar Sinan Güzel Sanatlar Üniversitesi', 'İstanbul'),
('Galatasaray Üniversitesi', 'İstanbul'),
('İstanbul Medeniyet Üniversitesi', 'İstanbul'),
('Türk-Alman Üniversitesi', 'İstanbul'),
('Sağlık Bilimleri Üniversitesi', 'İstanbul'),
('Milli Savunma Üniversitesi', 'İstanbul'),
('Koç Üniversitesi', 'İstanbul'),
('Sabancı Üniversitesi', 'İstanbul'),
('Bahçeşehir Üniversitesi', 'İstanbul'),
('Beykent Üniversitesi', 'İstanbul'),
('İstanbul Bilgi Üniversitesi', 'İstanbul'),
('Doğuş Üniversitesi', 'İstanbul'),
('Haliç Üniversitesi', 'İstanbul'),
('Işık Üniversitesi', 'İstanbul'),
('Kadir Has Üniversitesi', 'İstanbul'),
('Maltepe Üniversitesi', 'İstanbul'),
('İstanbul Okan Üniversitesi', 'İstanbul'),
('Özyeğin Üniversitesi', 'İstanbul'),
('Piri Reis Üniversitesi', 'İstanbul'),
('Yeditepe Üniversitesi', 'İstanbul'),
('Acıbadem Mehmet Ali Aydınlar Üniversitesi', 'İstanbul'),
('İstanbul Aydın Üniversitesi', 'İstanbul'),
('İstanbul Arel Üniversitesi', 'İstanbul'),
('İstanbul Esenyurt Üniversitesi', 'İstanbul'),
('İstanbul Gelişim Üniversitesi', 'İstanbul'),
('İstanbul Kültür Üniversitesi', 'İstanbul'),
('İstanbul Medipol Üniversitesi', 'İstanbul'),
('İstanbul Ticaret Üniversitesi', 'İstanbul'),
('Nişantaşı Üniversitesi', 'İstanbul'),
('Üsküdar Üniversitesi', 'İstanbul'),
('Fatih Sultan Mehmet Vakıf Üniversitesi', 'İstanbul'),
('İbn Haldun Üniversitesi', 'İstanbul'),
('İstanbul 29 Mayıs Üniversitesi', 'İstanbul'),
('İstanbul Sabahattin Zaim Üniversitesi', 'İstanbul'),
('Altınbaş Üniversitesi', 'İstanbul'),
('Biruni Üniversitesi', 'İstanbul'),
('İstinye Üniversitesi', 'İstanbul'),
('MEF Üniversitesi', 'İstanbul'),
('İstanbul Rumeli Üniversitesi', 'İstanbul'),
('İstanbul Atlas Üniversitesi', 'İstanbul'),
('İstanbul Galata Üniversitesi', 'İstanbul'),
('İstanbul Kent Üniversitesi', 'İstanbul'),
('İstanbul Topkapı Üniversitesi', 'İstanbul'),
('Beykoz Üniversitesi', 'İstanbul'),
('Bezmialem Vakıf Üniversitesi', 'İstanbul'),
('Demiroğlu Bilim Üniversitesi', 'İstanbul'),
('İstanbul Sağlık ve Teknoloji Üniversitesi', 'İstanbul'),
-- İzmir
('Ege Üniversitesi', 'İzmir'),
('Dokuz Eylül Üniversitesi', 'İzmir'),
('İzmir Yüksek Teknoloji Enstitüsü', 'İzmir'),
('İzmir Katip Çelebi Üniversitesi', 'İzmir'),
('İzmir Demokrasi Üniversitesi', 'İzmir'),
('İzmir Bakırçay Üniversitesi', 'İzmir'),
('Yaşar Üniversitesi', 'İzmir'),
('İzmir Ekonomi Üniversitesi', 'İzmir'),
('İzmir Tınaztepe Üniversitesi', 'İzmir'),
-- Adana
('Çukurova Üniversitesi', 'Adana'),
('Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi', 'Adana'),
('Çağ Üniversitesi', 'Mersin'),
-- Diğer iller (alfabetik)
('Adıyaman Üniversitesi', 'Adıyaman'),
('Afyon Kocatepe Üniversitesi', 'Afyonkarahisar'),
('Afyonkarahisar Sağlık Bilimleri Üniversitesi', 'Afyonkarahisar'),
('Ağrı İbrahim Çeçen Üniversitesi', 'Ağrı'),
('Aksaray Üniversitesi', 'Aksaray'),
('Amasya Üniversitesi', 'Amasya'),
('Akdeniz Üniversitesi', 'Antalya'),
('Antalya Bilim Üniversitesi', 'Antalya'),
('Alanya Alaaddin Keykubat Üniversitesi', 'Antalya'),
('Alanya Üniversitesi', 'Antalya'),
('Ardahan Üniversitesi', 'Ardahan'),
('Artvin Çoruh Üniversitesi', 'Artvin'),
('Aydın Adnan Menderes Üniversitesi', 'Aydın'),
('Balıkesir Üniversitesi', 'Balıkesir'),
('Bandırma Onyedi Eylül Üniversitesi', 'Balıkesir'),
('Bartın Üniversitesi', 'Bartın'),
('Batman Üniversitesi', 'Batman'),
('Bayburt Üniversitesi', 'Bayburt'),
('Bilecik Şeyh Edebali Üniversitesi', 'Bilecik'),
('Bingöl Üniversitesi', 'Bingöl'),
('Bitlis Eren Üniversitesi', 'Bitlis'),
('Bolu Abant İzzet Baysal Üniversitesi', 'Bolu'),
('Burdur Mehmet Akif Ersoy Üniversitesi', 'Burdur'),
('Bursa Uludağ Üniversitesi', 'Bursa'),
('Bursa Teknik Üniversitesi', 'Bursa'),
('Mudanya Üniversitesi', 'Bursa'),
('Çanakkale Onsekiz Mart Üniversitesi', 'Çanakkale'),
('Çankırı Karatekin Üniversitesi', 'Çankırı'),
('Hitit Üniversitesi', 'Çorum'),
('Pamukkale Üniversitesi', 'Denizli'),
('Dicle Üniversitesi', 'Diyarbakır'),
('Düzce Üniversitesi', 'Düzce'),
('Trakya Üniversitesi', 'Edirne'),
('Fırat Üniversitesi', 'Elazığ'),
('Erzincan Binali Yıldırım Üniversitesi', 'Erzincan'),
('Atatürk Üniversitesi', 'Erzurum'),
('Erzurum Teknik Üniversitesi', 'Erzurum'),
('Eskişehir Osmangazi Üniversitesi', 'Eskişehir'),
('Anadolu Üniversitesi', 'Eskişehir'),
('Eskişehir Teknik Üniversitesi', 'Eskişehir'),
('Gaziantep Üniversitesi', 'Gaziantep'),
('Gaziantep İslam Bilim ve Teknoloji Üniversitesi', 'Gaziantep'),
('Hasan Kalyoncu Üniversitesi', 'Gaziantep'),
('SANKO Üniversitesi', 'Gaziantep'),
('Giresun Üniversitesi', 'Giresun'),
('Gümüşhane Üniversitesi', 'Gümüşhane'),
('Hakkari Üniversitesi', 'Hakkari'),
('Hatay Mustafa Kemal Üniversitesi', 'Hatay'),
('İskenderun Teknik Üniversitesi', 'Hatay'),
('Iğdır Üniversitesi', 'Iğdır'),
('Süleyman Demirel Üniversitesi', 'Isparta'),
('Isparta Uygulamalı Bilimler Üniversitesi', 'Isparta'),
('Kahramanmaraş Sütçü İmam Üniversitesi', 'Kahramanmaraş'),
('Kahramanmaraş İstiklal Üniversitesi', 'Kahramanmaraş'),
('Karabük Üniversitesi', 'Karabük'),
('Karamanoğlu Mehmetbey Üniversitesi', 'Karaman'),
('Kafkas Üniversitesi', 'Kars'),
('Kastamonu Üniversitesi', 'Kastamonu'),
('Erciyes Üniversitesi', 'Kayseri'),
('Abdullah Gül Üniversitesi', 'Kayseri'),
('Kayseri Üniversitesi', 'Kayseri'),
('Nuh Naci Yazgan Üniversitesi', 'Kayseri'),
('Kırıkkale Üniversitesi', 'Kırıkkale'),
('Kırklareli Üniversitesi', 'Kırklareli'),
('Kırşehir Ahi Evran Üniversitesi', 'Kırşehir'),
('Kilis 7 Aralık Üniversitesi', 'Kilis'),
('Kocaeli Üniversitesi', 'Kocaeli'),
('Gebze Teknik Üniversitesi', 'Kocaeli'),
('Kocaeli Sağlık ve Teknoloji Üniversitesi', 'Kocaeli'),
('Selçuk Üniversitesi', 'Konya'),
('Necmettin Erbakan Üniversitesi', 'Konya'),
('Konya Teknik Üniversitesi', 'Konya'),
('KTO Karatay Üniversitesi', 'Konya'),
('Konya Gıda ve Tarım Üniversitesi', 'Konya'),
('Kütahya Dumlupınar Üniversitesi', 'Kütahya'),
('Kütahya Sağlık Bilimleri Üniversitesi', 'Kütahya'),
('İnönü Üniversitesi', 'Malatya'),
('Malatya Turgut Özal Üniversitesi', 'Malatya'),
('Manisa Celal Bayar Üniversitesi', 'Manisa'),
('Mardin Artuklu Üniversitesi', 'Mardin'),
('Mersin Üniversitesi', 'Mersin'),
('Tarsus Üniversitesi', 'Mersin'),
('Toros Üniversitesi', 'Mersin'),
('Muğla Sıtkı Koçman Üniversitesi', 'Muğla'),
('Muş Alparslan Üniversitesi', 'Muş'),
('Nevşehir Hacı Bektaş Veli Üniversitesi', 'Nevşehir'),
('Niğde Ömer Halisdemir Üniversitesi', 'Niğde'),
('Ordu Üniversitesi', 'Ordu'),
('Osmaniye Korkut Ata Üniversitesi', 'Osmaniye'),
('Recep Tayyip Erdoğan Üniversitesi', 'Rize'),
('Sakarya Üniversitesi', 'Sakarya'),
('Sakarya Uygulamalı Bilimler Üniversitesi', 'Sakarya'),
('Ondokuz Mayıs Üniversitesi', 'Samsun'),
('Samsun Üniversitesi', 'Samsun'),
('Siirt Üniversitesi', 'Siirt'),
('Sinop Üniversitesi', 'Sinop'),
('Sivas Cumhuriyet Üniversitesi', 'Sivas'),
('Sivas Bilim ve Teknoloji Üniversitesi', 'Sivas'),
('Harran Üniversitesi', 'Şanlıurfa'),
('Şırnak Üniversitesi', 'Şırnak'),
('Tekirdağ Namık Kemal Üniversitesi', 'Tekirdağ'),
('Tokat Gaziosmanpaşa Üniversitesi', 'Tokat'),
('Karadeniz Teknik Üniversitesi', 'Trabzon'),
('Trabzon Üniversitesi', 'Trabzon'),
('Avrasya Üniversitesi', 'Trabzon'),
('Munzur Üniversitesi', 'Tunceli'),
('Uşak Üniversitesi', 'Uşak'),
('Van Yüzüncü Yıl Üniversitesi', 'Van'),
('Yalova Üniversitesi', 'Yalova'),
('Yozgat Bozok Üniversitesi', 'Yozgat'),
('Zonguldak Bülent Ecevit Üniversitesi', 'Zonguldak')
on conflict (name) do nothing;
